steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy slashgather-bot \
          --source . \
          --region us-central1 \
          --platform managed \
          --no-allow-unauthenticated \
          --set-env-vars ENVIRONMENT=production,MONGODB_DB_NAME=gatherdb,DEFAULT_BALANCE=100.0 \
          --set-secrets DISCORD_TOKEN=DISCORD_TOKEN:latest \
          --set-secrets MONGODB_URI=MONGODB_URI:latest \
          --set-secrets MONGODB_DB_NAME=MONGODB_DB_NAME:latest \
          --set-env-vars DEFAULT_BALANCE=100.0 \
          --min-instances 1 \
          --max-instances 5 \
          --memory 512Mi \
          --timeout 300

options:
  logging: CLOUD_LOGGING_ONLY